# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Tarea de Build
- task: Maven@3
  displayName: 'Build and Package'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'clean package'
    
# Tarea de Test
- task: Maven@3
  displayName: 'Run Unit Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test surefire-report:report-only'

# Publicar Artefactos HTML
- task: PublishPipelineArtifact@1
  displayName: 'Publish Test Report'
  inputs:
    targetPath: 'target/site/surefire-report.html'
    artifactName: 'TestReport'
