# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

    
# Task  Build and Unit Test
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'
#    sonarQubeRunAnalysis: true

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'  # Esta opción puede ser 'Default' o especificar una versión
    mavenAuthenticateFeed: false  # Configura si es necesario autenticar el feed de Maven
    effectivePomSkip: false  # Opcional: determina si se debe omitir la generación del POM efectivo
#    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'pom'  # Usa la versión del plugin definida en el POM
    goals: 'package'  # La opción de 'goals' está disponible en Maven@4 para definir los objetivos a ejecutar
# Publicar Artefactos HTML
- task: PublishPipelineArtifact@1
  displayName: 'Publish Test Report'
  inputs:
    targetPath: 'target/site/surefire-report.html'
    artifactName: 'TestReport'


#- task: dependency-check-build-task@6
#  inputs:
#    projectName: 'thomaspena.helloworld'
#    scanPath: '$(System.DefaultWorkingDirectory)'
#    format: 'HTML, JUNIT, XML'          

#- task: PublishTestResults@2
#  displayName: Publish Dependency Check Test Results
#  inputs:
#    testResultsFormat: 'JUnit'
#    testResultsFiles: 'dependency-check\*junit.xml'
#    searchFolder: '$(Common.TestResultsDirectory)'

#- task: Maven@3
#  displayName: 'Dependency Check'
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    goals: 'org.owasp:dependency-check-maven:check'
- task: PublishPipelineArtifact@1
  displayName: 'Publish Dependency Check Report'
  inputs:
    targetPath: 'target/dependency-check-report.html'
    artifactName: 'DependencyCheckReport'

- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'PruebaTecnica'
    scannerMode: 'Other'
    extraProperties: |
      # Propiedades adicionales que se pasarán al escáner, 
      # Coloque una clave=valor por línea, ejemplo: 
      # sonar.exclusions=**/*.bin 
      sonar.host.url=http://localhost:7000
      sonar.projectKey = PruebaTecnica_PruebaTecnica_AZDNOPrDa3Xf3DH7xVnz 
      sonar.projectName = PruebaTecnica
- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'


