# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'  # Esta opción puede ser 'Default' o especificar una versión
    mavenAuthenticateFeed: false  # Configura si es necesario autenticar el feed de Maven
    effectivePomSkip: false  # Opcional: determina si se debe omitir la generación del POM efectivo
#    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'pom'  # Usa la versión del plugin definida en el POM
    goals: 'test surefire-report:report-only'  # La opción de 'goals' está disponible en Maven@4 para definir los objetivos a ejecutar
# Publicar Artefactos HTML
- task: PublishPipelineArtifact@1
  displayName: 'Publish Test Report'
  inputs:
    targetPath: 'target/site/surefire-report.html'
    artifactName: 'TestReport'

#- task: dependency-check-build-task@6
#  inputs:
#    projectName: 'PruebaTest'
#    scanPath: './pom.xml'
#    format: 'HTML, JUNIT, XML'
#    uploadReports: true
 # Análisis de Dependencias
- task: Maven@4
  displayName: 'Run OWASP Dependency Check'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'org.owasp:dependency-check-maven:check'
    options: '-Dformat=ALL'

# Publicar Resultados de Análisis de Dependencias
- task: PublishTestResults@2
  displayName: 'Publish Dependency Check Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/dependency-check-report.xml'
    searchFolder: '$(Build.SourcesDirectory)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Dependency Check Report'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/target'
    artifactName: 'DependencyCheckReport'   
#- task: SonarQubePrepare@6
#  inputs:
#    SonarQube: 'PruebaTecnica'
#    scannerMode: 'Other'
#    extraProperties: sonar.projectKey = PruebaTecnica_PruebaTecnica_AZDNOPrDa3Xf3DH7xVnz 
#- task: SonarQubePublish@6
#  inputs:
#    pollingTimeoutSec: '300'


